ignored:
  - DL3018 # Allow unpinned packages
  - SC2016 # Ignore single-quotes (expansion not desired)
  - SC1072 # This one seems spurious (related to `for` syntax)
  - DL3059 # It's fine to have multiple consecutive runs
