ARG CRYSTAL_VERSION=1.1.1
FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine

WORKDIR /app

# Install the latest version of LibSSH2, ping
RUN apk add --update --no-cache \
  bash \
  ca-certificates \
  iputils \
  libssh2-static \
  yaml-static

# Add trusted CAs for communicating with external services
RUN update-ca-certificates

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

COPY shard.yml /app
COPY shard.lock /app

RUN shards install --ignore-crystal-version

COPY scripts/* /app/scripts/

RUN mkdir -p /app/bin/drivers

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD /app/scripts/entrypoint.sh
