ARG crystal_version=1.0.0
FROM crystallang/crystal:${crystal_version}-alpine

WORKDIR /app

# Set the commit through a build arg
ARG PLACE_COMMIT="DEV"

# Ensure up-to-date dependencies
RUN apk upgrade --no-cache

# Install the latest version of LibSSH2, ping
RUN apk add --no-cache \
  bash \
  ca-certificates \
  iputils \
  libssh2-static \
  yaml-static

# Add trusted CAs for communicating with external services
RUN update-ca-certificates

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec
RUN apk add --no-cache bash

COPY shard.yml /app
COPY shard.override.yml /app
COPY shard.lock /app

RUN shards install --ignore-crystal-version

COPY scripts/* /app/scripts/

RUN mkdir -p /app/bin/drivers

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD /app/scripts/entrypoint.sh
